name: homestead-ledger

services:
  homestead-ledger:
    image: ghcr.io/tboltsp951/zimaos-homestead-ledger:latest@sha256:b5771e9262dc1b437511f367b262a9ee8b0343c0baf4fcdfcd8d021706fda2e1
    network_mode: bridge
    ports:
      - target: 8080
        published: "8190"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
    environment:
      PORT: "8080"
      DATA_DIR: /data
    container_name: homestead-ledger
x-casaos:
  id: org.tbolt.homesteadledger
  main: homestead-ledger
  icon: https://cdn.jsdelivr.net/gh/tboltsp951/zimaos-store@gh-pages/apps/org.tbolt.homesteadledger/assets/icon.svg
  title:
    en_US: Homestead Ledger
  index: /
  port_map: "8190"
  version: "1.0.0"
