name: garage-log

services:
  garage-log:
    image: ghcr.io/tboltsp951/zimaos-garage-log:latest
    network_mode: bridge
    ports:
      - target: 8080
        published: "8194"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
    environment:
      PORT: "8080"
      DATA_DIR: /data
    container_name: garage-log
x-casaos:
  id: org.tbolt.garagelog
  main: garage-log
  icon: https://cdn.jsdelivr.net/gh/tboltsp951/zimaos-store@gh-pages/apps/org.tbolt.garagelog/assets/icon.svg
  title:
    en_US: Garage Log
  index: /
  port_map: "8194"
  version: "1.0.0"
