name: cold-vault

services:
  cold-vault:
    image: ghcr.io/tboltsp951/zimaos-crypto-vault:latest@sha256:0b6d56f57b1dc1a7c8a3f34e27572d1b4bccdbca02c371ea146b0ec19b52d33f
    pull_policy: always
    network_mode: bridge
    ports:
      - target: 8080
        published: "8193"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
    environment:
      PORT: "8080"
      DATA_DIR: /data
    container_name: cold-vault
x-casaos:
  id: org.tbolt.coldvault
  main: cold-vault
  icon: https://cdn.jsdelivr.net/gh/tboltsp951/zimaos-store@gh-pages/apps/org.tbolt.coldvault/assets/icon.svg
  title:
    en_US: Cold Vault
  index: /
  port_map: "8193"
  version: "1.1.0"
